# Generated by Django 5.1 on 2024-09-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pro041Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("codigo", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "db_table": "pro_041_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pro042Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("dimesion", models.CharField(blank=True, max_length=255, null=True)),
                ("peso", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "pro_042_producto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pro043ProductoValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateField()),
                ("fecha_actualizacion", models.DateField(blank=True, null=True)),
                ("valor", models.IntegerField()),
                ("cantidad", models.IntegerField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pro_043_producto_valor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pro044Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen_083_id", models.IntegerField()),
                (
                    "nombre_archivo",
                    models.ImageField(blank=True, null=True, upload_to="producto"),
                ),
            ],
            options={
                "db_table": "pro_044_imagen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pro045Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "pro_045_marca",
                "managed": False,
            },
        ),
    ]
